name: country_selector
description: A flutter widget, You can use it to get region code and this widget allows you to filter
  the country code items by app bar search or the right side index bar.
version: 1.0.2+2
homepage: https://github.com/arisorgcn/country_selector

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # chinese pinyin tools
  # 拼音转换工具 (https://github.com/flutterchina/lpinyin)
  lpinyin: ^1.1.0

  # page transition
  page_transition: ^1.1.7+5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - packages/country_selector/i18n/en.json
    - packages/country_selector/i18n/es.json
    - packages/country_selector/i18n/ko.json
    - packages/country_selector/i18n/zh.json
